name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "feature/**", "refactor/**", "fix/**", "hotfix/**", ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lintagem Estática
    steps:
    - name: Faz checkout no Pull Request
      uses: actions/checkout@v3
    - name: Configura rustfmt
      uses: actions-rs/toolchain@v1.0.6
      with:
        profile: minimal
        toolchain: nightly
        override: true
        components: rustfmt
    - name: Executa verificação de formatação do código
      uses: actions-rs/cargo@v1.0.1
      with:
        command: fmt
        args: --all -- --check

  test:
    runs-on: ubuntu-latest
    needs: lint
    name: Testes
    steps:
    - name: Faz checkout no Pull Request
      uses: actions/checkout@v3
    - name: Faz build da biblioteca
      uses: actions-rs/cargo@v1.0.1
      with:
        command: buid
        args: --all
    - name: Executa testes
      uses: actions-rs/cargo@v1.0.1
      with:
        command: test
        args: --all
